runserver: _database
    python manage.py runserver

check:
    python manage.py check

shell: _database
    python manage.py shell

clean:
    find . -name '*.pyc' -exec rm {} \;

makemigrations app: _database
    python manage.py makemigrations {{ app }}

migrate: _database
    python manage.py migrate

startapp app:
    python manage.py startapp {{ app }}

sql app migration_id:
    python manage.py sqlmigrate {{ app }} {{ migration_id }}

createsu: _database
    python manage.py createsuperuser

dumpdata output: _database
    python manage.py dumpdata --indent=2 --output={{ output }}

loaddata input: _database
    python manage.py loaddata {{ input }}

_database:
    #!/usr/bin/env bash
    if   [[ $OSTYPE == "linux-gnu"* ]]; then
        sudo service postgresql status &> /dev/null || sudo service postgresql start
    elif [[ $OSTYPE == "darwin"* ]]; then
        pgrep -x postgres || open /Applications/Postgres.app
    fi
