runserver: launch_postgres
    python manage.py runserver

check:
    python manage.py check

shell: launch_postgres
    python manage.py shell

launch_postgres:
    #!/usr/bin/env bash
    # Launch Postgres.app if not running yet
    # Currently it only works for MacOS
    if [[ $OSTYPE == "darwin"* ]]; then
        if [ -z $(pgrep -x postgres) ]; then
            open /Applications/Postgres.app
        fi
    fi

clean:
    find . -name '*.pyc' -exec rm {} \;

makemigrations app: launch_postgres
    python manage.py makemigrations {{ app }}

migrate: launch_postgres
    python manage.py migrate

startapp app:
    python manage.py startapp {{ app }}

sql app migration_id:
    python manage.py sqlmigrate {{ app }} {{ migration_id }}

createsu:
    python manage.py createsuperuser

dumpdata output:
    python manage.py dumpdata --indent=2 --output={{ output }}

loaddata input:
    python manage.py loaddata {{ input }}
