open_cmd := if os() == "linux" { "xdg-open" } else { "open" }
project_url := "http://127.0.0.1:8000"
rabbitmq_url := "http://127.0.0.1:15672"
flower_url := "http://127.0.0.1:5555"
gitignore_file := ".gitignore"
gitignore_contents := "*.pyc\n.venv\ndb.sqlite3\n.env\n/media\n/static"
req_file := "requirements.txt"
req_contents := "django"

alias mm := mmigrate
alias sh := shell
alias doc := djangodoc

# Run development server
runserver: _database _rabbitmq
    python manage.py runserver

# Make a Python virtualenv
mkvenv: _mkignore _mkreq
    python -m venv .venv --prompt $(dirname "$0")

# Run development server on all interfaces at port 80
runserver0: _database _rabbitmq
    python manage.py runserver 0.0.0.0:80

# Check whole project
check:
    python manage.py check

# Open project in web browser
open:
    {{ open_cmd }} {{ project_url }}

# Open python shell with django settings
shell: _database
    python manage.py shell

# Clean all precompiled python files
clean:
    find . -name '*.pyc' -exec rm {} \;

# Create database migrations for single app or whole project
makemigrations app="": _database
    python manage.py makemigrations {{ app }}

# Run pending migrations for single app or whole project
migrate app="": _database
    python manage.py migrate {{ app }}

# Run both makemigrations & migrate commands
mmigrate app="": _database
    python manage.py makemigrations {{ app }} && python manage.py migrate {{ app }}

# Show database migrations for single app or whole project
showmigrations app="": _database
    python manage.py showmigrations {{ app }}

# Create a new app (also adding it to INSTALLED_APPS)
startapp app:
    #!/usr/bin/env bash
    python manage.py startapp {{ app }}
    APP_CLASS={{ app }}
    APP_CONFIG="{{ app }}.apps.${APP_CLASS^}Config"
    perl -0pi -e "s/(INSTALLED_APPS *= *\[)(.*?)(\])/\1\2    '$APP_CONFIG',\n\3/smg" $(find . -name settings.py)

# Delete an existing app
deleteapp app:
    #!/usr/bin/env bash
    read -p 'Do you wish to delete "{{ app }}" app? ' -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        rm -fr {{ app }}
    fi

# Show SQL behind a migration for a single app
sql app migration_id:
    python manage.py sqlmigrate {{ app }} {{ migration_id }}

# Create superuser for django admin
createsu: _database
    python manage.py createsuperuser

# Dump database data in json format
dumpdata output: _database
    python manage.py dumpdata --indent=2 --output={{ output }}

# Load database data from json format
loaddata input: _database
    python manage.py loaddata {{ input }}

# Open debug python shell with django settings
dshell:
    python manage.py debugsqlshell

# Copy static assets to STATIC_ROOT
collectstatic:
    python manage.py collectstatic

# Launch celery worker
celery: _rabbitmq
    celery -A myshop worker -l info

# Launch celery worker for flower (monitoring)
flower: _rabbitmq
    celery -A myshop flower

# Open admin dashboard for rabbitmq in web browser
rabbitmq-admin: _rabbitmq
    {{ open_cmd }} {{ rabbitmq_url }}

# Open admin dashboard for flower in web browser
flower-admin: flower
    {{ open_cmd }} {{ flower_url }}

# Launch stripe-cli and forward to local webhooks
stripe:
    stripe listen --forward-to 127.0.0.1:8000/payment/webhook/

# Open Django documentation for query
djangodoc query:
    #!/usr/bin/env bash
    if [ -z $VIRTUALENV ]; then
        DJANGO_VERSION=$(python -m django --version)
    else
        DJANGO_VERSION=$(source .venv/bin/activate && python -m django --version)
    fi
    DJANGO_MAJOR_VERSION=$(echo $DJANGO_VERSION | perl -ne 's/(\d.\d).*/\1/; print')
    QUERY_URL="https://docs.djangoproject.com/en/${DJANGO_MAJOR_VERSION}/search/?q={{ query }}"
    {{ open_cmd }} $QUERY_URL

# Add messages to be translated
makemessages:
    django-admin makemessages --all

# Compile messages already translated
compilemessages:
    django-admin compilemessages

# Make a .gitignore file
_mkignore:
    #!/usr/bin/env bash
    if [ -f "{{ gitignore_file }}" ]; then
        echo '{{ gitignore_file }} already exists!'
    else
        echo '{{ gitignore_contents }}' > {{ gitignore_file }}
    fi

# Make a requirements.txt file
_mkreq:
    #!/usr/bin/env bash
    if [ -f "{{ req_file }}" ]; then
        echo '{{ req_file }} already exists!'
    else
        echo '{{ req_contents }}' > {{ req_file }}
    fi

# Start database server
_database:
    #!/usr/bin/env bash
    if [ ! -e *.sqlite3 ]; then
        if   [[ $OSTYPE == "linux-gnu"* ]]; then
            sudo service postgresql status &> /dev/null || sudo service postgresql start
        elif [[ $OSTYPE == "darwin"* ]]; then

            pgrep -x postgres || open /Applications/Postgres.app
        fi
    fi

# Start redis server
_redis:
    #!/usr/bin/env bash
    if   [[ $OSTYPE == "linux-gnu"* ]]; then
        sudo service redis status &> /dev/null || sudo service redis start
    elif [[ $OSTYPE == "darwin"* ]]; then
        pgrep -x redis || open /Applications/Redis.app
    fi

# Start rabbitmq server
_rabbitmq:
    #!/usr/bin/env bash
    if   [[ $OSTYPE == "linux-gnu"* ]]; then
        sudo service rabbitmq-server status &> /dev/null || sudo service rabbitmq-server start
    elif [[ $OSTYPE == "darwin"* ]]; then
        pgrep -x rabbitmq || open /Applications/RabbitMQ.app
    fi
